<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import { DtPageView } from '@/components/ui/layout'
import { DtDataTable, type DtColumn } from '@/components/ui/data-table'
import { DtBadge } from '@/components/ui/badge'
import CodeBlock from '@/partials/CodeBlock.vue'

const { t } = useI18n()

const commands = [
  { cmd: 'npx dt-ui init', desc: 'Initialize the registry in the current project. Writes .dtui.json, copies base.css and lib/utils.ts, creates AGENT.md.' },
  { cmd: 'npx dt-ui list', desc: 'List every component in the registry with installed status.' },
  { cmd: 'npx dt-ui add <name…>', desc: 'Copy one or more components into src/components/ui/. Resolves internal deps and installs npm peer deps.' },
  { cmd: 'npx dt-ui update', desc: 'Refresh shared files (base.css, lib/utils.ts, AGENT.md). Optionally re-copies installed components — confirms before overwriting.' },
]

const cols: DtColumn[] = [
  { key: 'cmd', label: 'Command', width: '40%' },
  { key: 'desc', label: 'What it does' },
]

const initExample = `npx dt-ui init`

const addExample = `# Add several at once — internal deps auto-resolve
npx dt-ui add layout dialog button input

# Or pick interactively (no args)
npx dt-ui add`

const updateExample = `npx dt-ui update`
</script>

<template>
  <DtPageView :title="t('pages.cli.title')">
    <div class="dx-doc">
      <p class="dx-lead" v-html="t('pages.cli.lead')" />

      <h2>Commands</h2>
      <DtDataTable :columns="cols" :items="commands">
        <template #cmd="{ item }">
          <code>{{ (item as { cmd: string }).cmd }}</code>
        </template>
        <template #desc="{ item }">{{ (item as { desc: string }).desc }}</template>
      </DtDataTable>

      <h2>init</h2>
      <p>Run once at the start of a project. Asks a few questions about framework and target directories.</p>
      <CodeBlock :code="initExample" lang="bash" />
      <p>
        After init you'll have <code>.dtui.json</code> at the root, <code>src/styles/base.css</code>,
        <code>src/styles/table-cells.css</code>, <code>src/lib/utils.ts</code>, and an
        <code>AGENT.md</code> file your AI assistant can read for full component reference.
      </p>

      <h2>add</h2>
      <p>The most common command. Copies <code>.vue</code> + <code>index.ts</code> into your tree.</p>
      <CodeBlock :code="addExample" lang="bash" />
      <p>
        If a component declares an internal dep (e.g. <code>dialog</code> needs <code>button</code>),
        the CLI will ask before pulling it in. NPM peer dependencies (e.g. <code>reka-ui</code>) are
        installed automatically using your detected package manager.
      </p>

      <h2>update</h2>
      <p>
        Use after upgrading <code>aetherx-dt-ui</code>. Updates the shared style file, the helper
        utilities, and the agent reference. Optionally re-copies installed components, but
        <DtBadge variant="orange" size="sm">always asks first</DtBadge>
        — local edits are sacred.
      </p>
      <CodeBlock :code="updateExample" lang="bash" />

      <h2>Config file</h2>
      <p><code>.dtui.json</code> is generated by <code>init</code> and updated by <code>add</code>.</p>
      <CodeBlock :code='`{
  "framework": "vue-vite",
  "componentsDir": "src/components/ui",
  "libDir": "src/lib",
  "stylesDir": "src/styles",
  "installedComponents": ["button", "input", "card"],
  "agent": true
}`' lang="json" />
      <p>You normally don't edit this directly. The CLI mutates it as you add components.</p>
    </div>
  </DtPageView>
</template>
